spring:
  application:
    name: camp-registration
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        use_sql_comments: true


  datasource:
    url: jdbc:postgresql://localhost:15432/camp_registration
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:15432/camp_registration
    user: postgres
    password: 1234567890
    clean-disabled: false
    schemas: public, business, dictionaries
