CREATE TABLE dictionaries.registration_status
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32)                              NOT NULL,
    CONSTRAINT pk_registration_status PRIMARY KEY (id)
);

CREATE TABLE business.payment_check
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data            BYTEA,
    registration_id INTEGER,
    CONSTRAINT pk_payment_check PRIMARY KEY (id)
);

CREATE TABLE business.registration
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(32)                              NOT NULL,
    last_name              VARCHAR(32)                              NOT NULL,
    birthdate              TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    city                   VARCHAR(255)                             NOT NULL,
    registration_date      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    is_active              BOOLEAN                                  NOT NULL,
    phone                  VARCHAR(16)                              NOT NULL,
    is_medical_worker      BOOLEAN                                  NOT NULL,
    is_organizer           BOOLEAN                                  NOT NULL,
    church_id              INTEGER                                  NOT NULL,
    user_id                INTEGER                                  NOT NULL,
    registration_status_id INTEGER                                  NOT NULL,
    payment_type_id        INTEGER,
    admin_id               INTEGER                                  NOT NULL,
    CONSTRAINT pk_registration PRIMARY KEY (id)
);

CREATE TABLE business.registration_link_price
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_id INTEGER                                  NOT NULL,
    price_id        INTEGER                                  NOT NULL,
    CONSTRAINT pk_registration_link_price PRIMARY KEY (id)
);

ALTER TABLE business.registration_link_price
    ADD CONSTRAINT uc_registration_link_price_price UNIQUE (price_id);

ALTER TABLE business.registration_link_price
    ADD CONSTRAINT uc_registration_link_price_registration UNIQUE (registration_id);

ALTER TABLE business.payment_check
    ADD CONSTRAINT FK_PAYMENT_CHECK_ON_REGISTRATION FOREIGN KEY (registration_id) REFERENCES business.registration (id);

ALTER TABLE business.registration_link_price
    ADD CONSTRAINT FK_REGISTRATION_LINK_PRICE_ON_PRICE FOREIGN KEY (price_id) REFERENCES business.price (id);

ALTER TABLE business.registration_link_price
    ADD CONSTRAINT FK_REGISTRATION_LINK_PRICE_ON_REGISTRATION FOREIGN KEY (registration_id) REFERENCES business.registration (id);

ALTER TABLE business.registration
    ADD CONSTRAINT FK_REGISTRATION_ON_ADMIN FOREIGN KEY (admin_id) REFERENCES business.admin (id);

ALTER TABLE business.registration
    ADD CONSTRAINT FK_REGISTRATION_ON_CHURCH FOREIGN KEY (church_id) REFERENCES business.church (id);

ALTER TABLE business.registration
    ADD CONSTRAINT FK_REGISTRATION_ON_PAYMENT_TYPE FOREIGN KEY (payment_type_id) REFERENCES dictionaries.payment_type (id);

ALTER TABLE business.registration
    ADD CONSTRAINT FK_REGISTRATION_ON_REGISTRATION_STATUS FOREIGN KEY (registration_status_id) REFERENCES dictionaries.registration_status (id);

ALTER TABLE business.registration
    ADD CONSTRAINT FK_REGISTRATION_ON_USER FOREIGN KEY (user_id) REFERENCES business."user" (id);

ALTER TABLE business.faq
    ALTER COLUMN answer SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN bank_card_number SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN bank_card_owner SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN bank_name SET NOT NULL;

ALTER TABLE business.price
    ALTER COLUMN camp_id SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN church_id SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN content SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN date SET NOT NULL;

ALTER TABLE business.camp
    ALTER COLUMN end_date SET NOT NULL;

ALTER TABLE business.price
    ALTER COLUMN end_date SET NOT NULL;

ALTER TABLE business."user"
    ALTER COLUMN first_name SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN for_bank_card SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN icon SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN is_deleted SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN is_read SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN is_super_admin SET NOT NULL;

ALTER TABLE business."user"
    ALTER COLUMN last_name SET NOT NULL;

ALTER TABLE business.camp
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE business.church
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE business."user"
    ALTER COLUMN phone SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN phone_number SET NOT NULL;

ALTER TABLE business."user"
    ALTER COLUMN photo_url SET NOT NULL;

ALTER TABLE business.faq
    ALTER COLUMN question SET NOT NULL;

ALTER TABLE business.camp
    ALTER COLUMN seats SET NOT NULL;

ALTER TABLE business.camp
    ALTER COLUMN start_date SET NOT NULL;

ALTER TABLE business.price
    ALTER COLUMN start_date SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN telegram_id SET NOT NULL;

ALTER TABLE business."user"
    ALTER COLUMN telegram_id SET NOT NULL;

ALTER TABLE business.notification
    ALTER COLUMN title SET NOT NULL;

ALTER TABLE business.admin
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE business.price
    ALTER COLUMN value SET NOT NULL;



ALTER TABLE dictionaries.payment_type
    ALTER COLUMN name SET NOT NULL;