CREATE SCHEMA IF NOT EXISTS business;

ALTER TABLE public.price
DROP
CONSTRAINT fk_price_on_camp;

DROP TABLE public.camp CASCADE;

DROP TABLE public.church CASCADE;

DROP TABLE public.notification CASCADE;

DROP TABLE public.price CASCADE;

CREATE TABLE business.camp
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(32),
    seats      INTEGER,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_camp PRIMARY KEY (id)
);

CREATE TABLE business.church
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32),
    CONSTRAINT pk_church PRIMARY KEY (id)
);

CREATE TABLE business.notification
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telegram_id VARCHAR(32),
    title       VARCHAR(64),
    content     VARCHAR(64),
    date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

CREATE TABLE business.price
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value      INTEGER,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    camp_id    INTEGER,
    CONSTRAINT pk_price PRIMARY KEY (id)
);

ALTER TABLE business.price
    ADD CONSTRAINT FK_PRICE_ON_CAMP FOREIGN KEY (camp_id) REFERENCES business.camp (id);