CREATE TABLE business."user"
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name   VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    phone       VARCHAR(255),
    photo_url   VARCHAR(255),
    telegram_id VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE business."user"
    ADD CONSTRAINT uc_user_telegram UNIQUE (telegram_id);