CREATE TABLE business.admin
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_card_number VARCHAR(255),
    bank_card_owner  VARCHAR(255),
    bank_name        VARCHAR(255),
    phone_number     VARCHAR(255),
    for_bank_card    BOOLEAN,
    is_super_admin   BOOLEAN,
    church_id        INTEGER,
    user_id          INTEGER,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

ALTER TABLE business.admin
    ADD CONSTRAINT uc_admin_user UNIQUE (user_id);

ALTER TABLE business.admin
    ADD CONSTRAINT FK_ADMIN_ON_CHURCH FOREIGN KEY (church_id) REFERENCES business.church (id);

ALTER TABLE business.admin
    ADD CONSTRAINT FK_ADMIN_ON_USER FOREIGN KEY (user_id) REFERENCES business."user" (id);