CREATE TABLE business.faq
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question VARCHAR(256),
    answer   VARCHAR(256),
    CONSTRAINT pk_faq PRIMARY KEY (id)
);

ALTER TABLE business.admin
ALTER
COLUMN bank_card_number TYPE VARCHAR(64) USING (bank_card_number::VARCHAR(64));

ALTER TABLE business.admin
ALTER
COLUMN bank_card_owner TYPE VARCHAR(64) USING (bank_card_owner::VARCHAR(64));

ALTER TABLE business.admin
ALTER
COLUMN bank_name TYPE VARCHAR(32) USING (bank_name::VARCHAR(32));

ALTER TABLE business.admin
ALTER
COLUMN phone_number TYPE VARCHAR(32) USING (phone_number::VARCHAR(32));